---

- shell: wget -qO- https://get.docker.com/ | sh
- shell: echo "DOCKER_OPTS=\"--insecure-registry registry-hub.hepsiburada.com:5000\"" >> /etc/default/docker
- shell: service docker restart
- shell: docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://registry-hub.hepsiburada.com/v1/scripts/6A09462B97B0433BDA1E:1435676400000:tZjlg1VJqbpb7CoQ7DAj8MiFRGg
- shell: docker run -ti -d --add-host tags.tiqcdn.com:192.168.57.91 -e AGENT_KEY=278b533a98da126532afa41eef9af63e -e GO_SERVER=ci.hepsiburada.com registry-hub.hepsiburada.com:5000/qa-box
